pipeline{
    agent{
    label {
        label 'slave-02'
        customWorkspace "/opt/jenkins-jobs"
    }
    }
    tools{
        jdk 'jdk'
        maven 'maven3'
    }
    //stages {
      //  stage('Build') {
        //    steps {
          //      sh 'mvn -B -DskipTests clean package'
            //}
        //}
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
